"""empty message

Revision ID: 3dc8453d444e
Revises: e1f87046c5c1
Create Date: 2020-02-28 17:04:04.967898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc8453d444e'
down_revision = 'e1f87046c5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    res = conn.execute("SELECT * FROM turnovers")
    results = res.fetchall()
    if results:
        print("\n\n!!! WARNING: DROPPING TABLE \"turnovers\" !!!\n"
              "Since it's not possible to auto-migrate the turnover entries, you must manually migrate them\n"
              "as replenishments (see https://github.com/g3n35i5/shop-db2/issues/28 for details.)\n"
              "\n"
              "!!! You still have entries in your turnovers table. Please migrate them manually before you continue!!!\n")
        return
    op.drop_table('turnovers')
    op.drop_table('turnoverrevokes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnoverrevokes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('turnover_id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('revoked IN (0, 1)'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['turnover_id'], ['turnovers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turnovers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=256), nullable=False),
    sa.CheckConstraint('revoked IN (0, 1)'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
