"""empty message

Revision ID: 8528842035bf
Revises: 97bd09d1c2b5
Create Date: 2020-02-27 14:38:52.290160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8528842035bf'
down_revision = '97bd09d1c2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('replenishmentcollections') as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(constraint_name='fk_seller_id', referent_table='users',
                                    local_cols=['seller_id'], remote_cols=['id'])

    conn = op.get_bind()
    conn.execute("UPDATE replenishmentcollections SET seller_id=1")

    with op.batch_alter_table('replenishmentcollections') as batch_op:
        batch_op.alter_column('seller_id', existing_type=sa.INTEGER(), nullable=False)

    print("\n\n!!! WARNING: column \"seller_id\" is set to 1 per default !!!\n"
          "Please change these default values\n")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replenishmentcollections', type_='foreignkey')
    op.drop_column('replenishmentcollections', 'seller_id')
    # ### end Alembic commands ###
