"""empty message

Revision ID: 97bd09d1c2b5
Revises: f7782a0f2777
Create Date: 2020-02-21 16:06:09.866020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bd09d1c2b5'
down_revision = 'f7782a0f2777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('image_upload_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(constraint_name='fk_image_upload_id', referent_table='uploads',
                                    local_cols=['image_upload_id'], remote_cols=['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'image_upload_id')
    # ### end Alembic commands ###
