"""empty message

Revision ID: e1f87046c5c1
Revises: 8528842035bf
Create Date: 2020-02-28 15:50:37.639242

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1f87046c5c1"
down_revision = "8528842035bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    res = conn.execute("SELECT * FROM refunds")
    results = res.fetchall()
    if results:
        print(
            '\n\n!!! WARNING: DROPPING TABLE "refunds" !!!\n'
            "Since it's not possible to auto-migrate the refund entries, you must manually migrate them\n"
            "as replenishments (see https://github.com/g3n35i5/shop-db2/issues/28 for details.)\n"
            "\n"
            "!!! You still have entries in your refunds table. Please migrate them manually before you continue!!!\n"
        )
        return
    op.drop_table("refunds")
    op.drop_table("refundrevokes")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refundrevokes",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.Column("revoked", sa.BOOLEAN(), nullable=False),
        sa.Column("refund_id", sa.INTEGER(), nullable=False),
        sa.Column("admin_id", sa.INTEGER(), nullable=False),
        sa.CheckConstraint("revoked IN (0, 1)"),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["refund_id"],
            ["refunds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refunds",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("admin_id", sa.INTEGER(), nullable=False),
        sa.Column("comment", sa.VARCHAR(length=64), nullable=False),
        sa.Column("revoked", sa.BOOLEAN(), nullable=False),
        sa.Column("total_price", sa.INTEGER(), nullable=False),
        sa.CheckConstraint("revoked IN (0, 1)"),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
