"""empty message

Revision ID: f7782a0f2777
Revises: a48d3896fd55
Create Date: 2020-02-20 10:02:22.842355

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f7782a0f2777"
down_revision = "a48d3896fd55"
branch_labels = None
depends_on = None


def upgrade():
    # Query all payoffs. If there are any, print user warning
    conn = op.get_bind()
    res = conn.execute("SELECT * FROM payoffs")
    results = res.fetchall()
    if results:
        print(
            '\n\n!!! WARNING: DROPPING TABLE "payoffs" !!!\n'
            "Since it's not possible to auto-migrate the payoff entries, you must manually migrate them\n"
            "as replenishments (see https://github.com/g3n35i5/shop-db2/issues/28 for details.)\n"
            "\n"
            "!!! You still have entries in your payoffs table. Please migrate them manually before you continue!!!\n"
        )
        return
    op.drop_table("payoffrevokes")
    op.drop_table("payoffs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payoffs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.Column("admin_id", sa.INTEGER(), nullable=False),
        sa.Column("comment", sa.VARCHAR(length=64), nullable=False),
        sa.Column("revoked", sa.BOOLEAN(), nullable=False),
        sa.Column("amount", sa.INTEGER(), nullable=False),
        sa.CheckConstraint("revoked IN (0, 1)"),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payoffrevokes",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.Column("revoked", sa.BOOLEAN(), nullable=False),
        sa.Column("payoff_id", sa.INTEGER(), nullable=False),
        sa.Column("admin_id", sa.INTEGER(), nullable=False),
        sa.CheckConstraint("revoked IN (0, 1)"),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payoff_id"],
            ["payoffs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
