name: Create coverage and send it to codacy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy configuration.example.py to configuration.py
      run: |
        cp configuration.example.py configuration.py

    - name: Update "Secret key"
      run: |
        sed -i 's/YouWillNeverGuess/YOURBETTERSUPERSECRETKEY/g' configuration.py

    - name: Run coverage
      run: |
        python test.py --mode auto

    - uses: actions/checkout@master
    - name: Run codacy-coverage-reporter
      uses: mrfyda/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
